name: featbit
services:
  ui:
    image: featbit/featbit-ui:latest
    environment:
      - API_URL
      - EVALUATION_URL
    depends_on:
      - api-server

  api-server:
    image: featbit/featbit-api-server:latest
    environment:
      - DbProvider=Postgres
      - MqProvider=Postgres
      - CacheProvider=None
      - Postgres__ConnectionString
      - OLAP__ServiceHost=http://da-server
    depends_on:
      - postgresql
      - da-server

  evaluation-server:
    image: featbit/featbit-evaluation-server:latest
    environment:
      - DbProvider=Postgres
      - MqProvider=Postgres
      - CacheProvider=None
      - Postgres__ConnectionString
    depends_on:
      - postgresql

  da-server:
    image: featbit/featbit-data-analytics-server:latest
    environment:
      DB_PROVIDER: Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: featbit
      CHECK_DB_LIVNESS: true
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15.10
    container_name: postgresql
    restart: on-failure
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./infra/postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
